server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 1234567890
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true

jwt:
  signerKey: "bYt3wEFmmEqzQy0rHHMoA2xx4ypt+DbEzjjrD3yTC/iHAQ2H2KM7SzgZeCmbI7kL"